---
title: "Project 2 - Task 2"
author: "Hazim Fitri P152419"
date: "`r Sys.Date()`"
output: 
  pdf_document:
    toc: true
    toc_depth: 6
---

```{r}
library(seewave)
library(rpanel)
library(tuneR)
```

# Roaring Lion Audio

```{r}
# upload data of a lion roar
lion = readMP3('Data/lion_roar.mp3')
plot(lion)
str(lion)
```

```{r}
# define plot for frequency spectrum analysis
plot.frequency.spectrum = function(X.k, xlimits = c(0, length(X.k))) {
  plot.data = cbind(0:(length(X.k) - 1), Mod(X.k))

  plot.data[2:length(X.k), 2] = 2 * plot.data[2:length(X.k), 2]

  plot(plot.data, t = "h", lwd = 2, 
       main = "Frequency Spectrum of (FFT) of Lion's Roar",
       xlab = "Frequency (Hz)", ylab = "Strength",
       xlim = xlimits, ylim = c(0,max(Mod(plot.data[,2]))))
}
```

```{r}
plot(lion, main = "Waveform Plot of Lion's Roar", xlab = "Time (seconds)")
```

```{r}
timer(lion, f=lion@samp.rate, 
      threshold=50, 
      msmooth=c(4000,0), 
      main = 'Timer Plot of Lion Roar')
```

This plot visualized the apli

```{r}
lion_r = fft(lion@left)  
plot.frequency.spectrum(lion_r)
```

The frequency spectrum plot above is generated from FFT of the left audio channel. The horizontal axis represent the range of frequencies in the signal while the vertical axis represent the strength of each frequency.

```{r}
spectro(lion, main = "Spectrogram of Lion Roar")
```

# Crying Man Audio

```{r}
# upload data of a crying man
cry = readMP3('Data/crying_man.mp3')
str(cry)
```

```{r}
plot(cry, main = "Waveform Plot of Man's Crying", xlab = "Time (seconds)")
```

```{r}
timer(cry, 
      f=cry@samp.rate, 
      threshold = 25, 
      msmooth = c(3000,0),
      main = 'Timer Plot of Man Crying')

```

```{r}
plot.frequency.spectrum = function(X.k, xlimits = c(0, length(X.k))) {
  plot.data = cbind(0:(length(X.k) - 1), Mod(X.k))

  plot.data[2:length(X.k), 2] = 2 * plot.data[2:length(X.k), 2]

  plot(plot.data, t = "h", lwd = 2, 
       main = "Frequency Spectrum of (FFT) of Man's Crying",
       xlab = "Frequency (Hz)", ylab = "Strength",
       xlim = xlimits, ylim = c(0,max(Mod(plot.data[,2]))))
}

cry_m = fft(cry@left)
plot.frequency.spectrum(cry_m)
```

```{r}
spectro(cry, main = 'Spectrogram of man crying')
```
