---
title: "Part 1 - Task 3"
output: html_document
---

```{r}
library(tm)
library(wordcloud2)
library(tidyverse)
library(textstem)
```

```{r}
path = "D:/01. Education/02. Master/Semester 2/Unstructured-Data-Analysis/Project 1 - 30%/Part 1/Part 1 - Task 3/Data"

file.names = list.files(path, pattern = "*.csv", full.names=TRUE)
```

```{r}
analysis = function(x){
  # read text data
  text = lapply(file.names, readLines)
  lyrics = text[[x]]
  
  # text cleaning
  toSpace = content_transformer(function(x, pattern) {
    return(gsub(pattern, " ", x))
  })

  toSpaceUnicode = content_transformer(function(x) {
    return(gsub("[\u2012\u2013\u2014\u2015-]", " ", x))
           })
  # custom stopwords
  custom_stop = c(stopwords("english"), "said", "will", "company", "ill", 
                  "chorus", "verse", "will", "tell", "just", "know", "see",
                  "right", "now", "can", "ever", "say", "let", "ooh", "ill",
                  "get", "like", "make", "back", "dip", "thats", "use", "keep", 
                  "check")
  
	docs = Corpus(VectorSource(lyrics))

  docs_clean = docs %>%
    tm_map(content_transformer(tolower)) %>%
    tm_map(toSpaceUnicode) %>%
    tm_map(removeNumbers) %>%
    tm_map(toSpace, "\\.") %>%
    tm_map(removePunctuation) %>%
    tm_map(removeWords, custom_stop) %>%
    tm_map(stripWhitespace)
  
  # lemmatization
  text_data = sapply(docs_clean, as.character)
  lemmatize_text =lemmatize_strings(text_data)
  docs.lem = Corpus(VectorSource(lemmatize_text))
  
  dtm = DocumentTermMatrix(docs.lem)
  
  freq = colSums(as.matrix(dtm))
  
  df = data.frame(term = names(freq), freq = freq)
  
  df = df %>%
    arrange(desc(freq))
  
  # visualize word cloud
  print(head(df, 5))
  print(wordcloud2(df, shape = "star"))
}
```

```{r}
# output from All too well - Taylor Swift lyrics
analysis(1)
```

```{r}
# output from Blue - Yung Kai lyrics
analysis(2)
```

```{r}
# output from Eminem - Rap God lyrics
analysis(3)
```

```{r}
# output for Fool's Garden - Lemon Tree
analysis(4)
```

```{r}
# output from Maher Zain - For The Rest of My Life lyrics
analysis(5)
```
